apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  ports:
    - nodePort: 31001
      port: 5001
      targetPort: 80
  selector:
    app: result-deployment
  type: NodePort