---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
spec:
  containers:
    - image: kodekloud/fileserver
      imagePullPolicy: IfNotPresent
      name: gop-fileserver
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /web
        name: data-store
        readOnly: true
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
